//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Mountian.rc
//
#define IDS_DESCRIPTION                 1
#define IDS_SPEED                       100
#define IDS_BEEACC                      101
#define IDS_WASPACC                     102
#define IDS_BEEVEL                      103
#define IDS_WASPVEL                     104
#define IDS_BEECOUNT                    105
#define IDS_CLS                         106
#define IDC_DEFAULT                     1100
#define IDC_CLS                         1101
#define IDC_SPEED                       1102
#define IDC_WASPVEL                     1103
#define IDC_WASPACC                     1104
#define IDC_BEEVEL                      1105
#define IDC_BEEACC                      1106
#define IDC_BEENUM                      1107
#define IDC_BEECOUNT                    1107

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
